services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - apps/server/.env
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  dbmate:
    image: amacneil/dbmate
    profiles: ['migrations']
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - apps/server/.env
    volumes:
      - ./apps/server/migrations:/db/migrations
    entrypoint: ['dbmate', 'up']

  web-app:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - path: apps/server/.env
        required: true
        format: raw
      - path: apps/web/.env
        required: true
        format: raw
    image: auction-web-app:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
      - '5173:5173'
    command: ['pnpm', 'run', '-r', 'dev']
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/server/node_modules
      - /app/apps/web/node_modules

volumes:
  db_data:
