services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: auction
      POSTGRES_PASSWORD: auctionpass
      POSTGRES_DB: auctiondb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  bidding-server:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - apps/server/.env
    environment:
      DATABASE_URL: postgres://auction:auctionpass@db:5432/auctiondb
    depends_on:
      - db
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    command: ['pnpm', '--filter', 'server', 'dev']
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data:
